baseURL = 'http://far.chickenkiller.com/'
languageCode = 'en-us'
title = "Farooq's site"
theme = "vitae"
paginate = 7
enableRobotsTXT = true

copyright = "(C) All rights are reserved under CC-BY-SA 4.0 for Farooq Karimi Zadeh"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/farooqkz"

[[params.social]]
name = "Mastodon"
icon = "fab fa-mastodon"
url = "https://qoto.org/@farooqkz"


[markup]
  [markup.highlight]
	anchorLineNos = false
	codeFences = true
	guessSyntax = false
	hl_Lines = ''
	lineAnchors = ''
	lineNoStart = 1
	lineNos = false
	lineNumbersInTable = true
	noClasses = true
	style = 'monokai'
	tabWidth = 4

[params]
  keywords = ["Farooq", "Farooq Karimi Zadeh", "farooqkz"]
  math = true
  favicon = true
  avatar = "/mylogo0.png"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Math"
url = "/math"
weight = 2

[[menu.main]]
name = "Computer Science"
url = "/computer"
weight = 3

[[menu.main]]
name = "Religion"
url = "/religion"
weight = 4

[[menu.main]]
name = "Other"
url = "/other"
weight = 5
